### ISSUE TITLE
App's stop to fetch details of spending

### ISSUE THREAD

**Issue by TomazMartins** [VisualizeMobile/AKANAndroid#1]
O aplicativo dá uma parada e interrompe o funcionamento após ser feita uma busca pelos detalhes dos gastos de um parlamentar. Isso ocorre apenas quando não há acesso à Internet. Essa exceção deve ser tratada.

---

The application pauses and stops operating after being made a search for the details of the spending of a congressman. This only occurs when there is no internet access. This exception should be treated.

**Comment by ArthurJahn** [comment]
I handled this issue dismissing the datepicker dialog. Worked fine.
Closed on commit f789cad7da8c144b5bddc87c74b3a5d0250d24ce
