### ISSUE TITLE
Approaching the end of the list

### ISSUE THREAD

**Issue by alvarofernandoms** [VisualizeMobile/AKANAndroid#2]
When I scroll down to the bottom, the scroll indicator disappear and the last congressman is not visible. Both bug it's caused by bottom menu bar. Here is some images to exemplify:
Image 01:
![captura de tela de 2015-05-14 09 46 29](https://cloud.githubusercontent.com/assets/3226069/7632163/b5649568-fa20-11e4-905a-3624b2cc195a.png)

Image 02:
![captura de tela de 2015-05-14 09 46 41](https://cloud.githubusercontent.com/assets/3226069/7632165/c1f23cd6-fa20-11e4-987b-c847b4d1a7df.png)

**Comment by TomazMartins** [comment]
We have already seen this, @alvarofernandoms .
One solution would be, at least provisionally, inserting an empty cell in end of the list, so that the last valid element may be visible above that empty cell.

**Comment by ArthurJahn** [comment]
Closed. Adding a margin_bottom for 70dp fixed the issue.
